version: '3'

services:
  postgres:
    container_name: dnd_postgres
    image: postgres
    environment:
      POSTGRES_USER: doterfather
      POSTGRES_PASSWORD: doterfather
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
